//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScriptRus1.rc
//
#define IDS_TB_RESET                    1
#define IDS_TB_RUN                      2
#define IDS_TB_PAUSE                    3
#define IDS_TB_STEP                     4
#define IDS_TB_RUN_BACK                 5
#define IDS_TB_STEP_BACK                6
#define IDS_TB_DRAG                     7
#define IDS_TB_MAGNIFY                  8
#define IDS_TB_ALIGN                    9
#define IDS_TB_VECTORS                  10
#define IDS_TB_GRID                     11
#define IDS_TB_USER_GRAPHIC             12
#define IDS_TB_RASTER                   13
#define IDS_TB_CONTROLS                 14
#define IDS_TB_BIND                     15
#define IDS_TB_SAVE_SEQUENCE            15
#define IDS_TB_SAVE_VS_SETTINGS         16
#define IDS_TB_SAVE_CTRL_SETTINGS       17
#define IDS_TB_LOAD_CTRL_SETTINGS       18
#define IDR_FRAME_MENU                  101
#define MAIN_MENU                       101
#define MAIN_TOOLBAR                    102
#define CURSOR_FLAT_HAND                106
#define CURSOR_MOVE_HAND                108
#define CURSOR_SCALE                    109
#define GRID_SETUP_DIALOG               110
#define ADJUST_SETUP_DIALOG             111
#define ADJUST_SETUP_PARAM_DIALOG       112
#define POPUP_MENU                      113
#define VECTORS_SETUP_DIALOG            114
#define IDI_VSHELL                      115
#define IDI_CHILD                       117
#define ABOUT_VSHELL_DIALOG             118
#define SAVE_SEQUENCE_AS_DIALOG         119
#define ACCELERATOR                     120
#define ED_STEP_X                       1001
#define ED_STEP_Y                       1002
#define BTN_COLOR                       1003
#define BTN_OK                          1004
#define BTN_CANCEL                      1005
#define BTN_APPLY                       1006
#define CH_ENABLE_ADJUST                1006
#define SL_CONTRAST                     1007
#define SL_BRIGHTNESS                   1008
#define SL_MULTIPLIER                   1009
#define LAB_CONTRAST                    1016
#define LAB_MULTIPLIER                  1017
#define LAB_BRIGHTNESS                  1018
#define BTN_CONTRAST_RESET              1019
#define BTN_BRIGHTNESS_RESET            1020
#define BTN_MULTIPLIER_SETUP            1021
#define BTN_VECTORS_COLOR               1021
#define ED_ASP_MUL_MIN                  1021
#define ED_ASP_MUL_CUR                  1022
#define ED_ASP_MUL_MAX                  1023
#define ED_ASP_MUL_STEP                 1024
#define LAB_OUT_MAX                     1026
#define BTN_SET_BY_IMAGE                1027
#define ED_ASP_BRIG_CUR                 1028
#define FRAME_HISTO                     1028
#define LAB_OUT_NULL                    1029
#define BOX_BRIGHTNESS                  1029
#define LAB_OUT_MIN                     1030
#define BOX_CONTRAST                    1030
#define BOX_MULTIPLIER                  1031
#define ST_HISTO_VALUE                  1032
#define ST_HISTO_PERCENT                1033
#define ED_FILENAME                     1033
#define BTN_BROWSE                      1034
#define RD_ASC_FILENAME                 1035
#define RD_ASK_FILENAME                 1035
#define RD_SPECIFY_FILENAME             1036
#define IDM_FILE_EXIT                   40003
#define MMF_EXIT                        40003
#define IDM_WIN_CASCADE                 40004
#define MMW_CASCADE                     40004
#define IDM_WIN_TILE                    40005
#define MMW_TILE                        40005
#define IDM_WIN_ARRANGE                 40006
#define MMW_ARRANGE                     40006
#define IDM_WIN_CLOSE                   40007
#define MMW_CLOSE                       40007
#define IDM_WIN_CONTROLS                40009
#define MMW_CONTROLS                    40009
#define MMO_RUN                         40012
#define MMO_PAUSE                       40014
#define MMO_STEP                        40016
#define MMO_BACK_STEP                   40019
#define MMO_STEP_BACK                   40020
#define MMO_START_BACK                  40021
#define MMO_RUN_BACK                    40022
#define MMO_BIND                        40024
#define MMO_GRID                        40031
#define MMO_ALIGN                       40032
#define MMO_DRAG                        40033
#define MMO_SCALE                       40034
#define MMS_GRID_SETUP                  40035
#define MMS_GRID                        40035
#define MMO_RESET                       40037
#define MMS_ADJUST                      40041
#define MMO_SHOW_OVERFLOWS              40043
#define MMS_VECTORS                     40046
#define MMO_VECTORS                     40047
#define MMF_SAVE_IMAGE                  40049
#define MMF_SAVE_SEQUENCE               40050
#define MMF_SAVE_SETTING                40051
#define MMO_RASTER                      40052
#define ID_SETUP                        40053
#define ID_OPERATE                      40054
#define MMF_SAVE_CONTROL_SETTING        40055
#define MMF_LOAD_CONTROL_SETTING        40056
#define MMO_SHOW_USER_GRAPHIC           40058
#define adsf                            40059
#define MMH_ABOUT_VSHELL                40060
#define MMO_SCALE_PLUS                  40061
#define MMO_SCALE_MINUS                 40062
#define ID_OPERATE_RECORD               40062
#define MMO_RECORD                      40063
#define ID_FILE_SAVESEQUENCE            40064
#define MMF_SAVE_DEF_SEQUENCE           40065
#define ID_POPUP_SAVESEQUENCE           40066
#define MMS_SAVE_SEQUENCE_IN            40067
#define ID_40068                        40068
#define MMS_SAVE_SEQUENCE_AS            40069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40070
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
